import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { afterEach, expect, it, vi } from 'vitest'
import { Welcome } from './Welcome'
import { api } from '../lib/community'
vi.mock('../lib/community',()=>({api:vi.fn()}))
afterEach(()=>{cleanup();vi.mocked(api).mockReset()})
it('resets through a host code, requires matching passwords, and returns to sign in',async()=>{
 vi.mocked(api).mockResolvedValue({setup:false})
 render(<MemoryRouter><Welcome onLogin={vi.fn()}/></MemoryRouter>)
 fireEvent.click(await screen.findByRole('button',{name:'Forgot password?'}))
 expect(screen.getByText(/No reset email/)).toBeInTheDocument()
 fireEvent.change(screen.getByLabelText('Reset code'),{target:{value:' fixture-code '}})
 fireEvent.change(screen.getByLabelText('New password'),{target:{value:'new fixture password'}})
 fireEvent.change(screen.getByLabelText('Confirm new password'),{target:{value:'different password'}})
 fireEvent.click(screen.getByRole('button',{name:'Reset password'}))
 expect(await screen.findByRole('alert')).toHaveTextContent('do not match')
 expect(api).not.toHaveBeenCalledWith('/auth/password/reset',expect.anything(),expect.anything())
 fireEvent.change(screen.getByLabelText('Confirm new password'),{target:{value:'new fixture password'}})
 fireEvent.click(screen.getByRole('button',{name:'Reset password'}))
 expect(await screen.findByRole('status')).toHaveTextContent('All previous sessions are signed out')
 expect(api).toHaveBeenCalledWith('/auth/password/reset','POST',{token:'fixture-code',password:'new fixture password'})
 fireEvent.click(screen.getByRole('button',{name:'Back to sign in'}))
 expect(screen.getByRole('button',{name:/Sign in/})).toBeInTheDocument()
})
it('says where accounts live on a server',async()=>{
 vi.mocked(api).mockResolvedValue({setup:false,public_url:'https://grove.example.test'})
 render(<MemoryRouter><Welcome onLogin={vi.fn()}/></MemoryRouter>)
 expect(await screen.findByText(/on its server, grove\.example\.test\./)).toBeInTheDocument()
})
it('asks for the installer setup code before the host account, filled from the setup link',async()=>{
 window.history.pushState({},'','/community?setup=river-stone-4821')
 vi.mocked(api).mockImplementation(async(path)=>path==='/auth/status'?{setup:true,setup_code:true,public_url:'https://grove.example.test'}:{id:'u',name:'Host',email:'host@example.test',admin:1})
 const onLogin=vi.fn()
 render(<MemoryRouter><Welcome onLogin={onLogin}/></MemoryRouter>)
 expect(await screen.findByLabelText('Setup code')).toHaveValue('river-stone-4821')
 fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Host'}})
 fireEvent.change(screen.getByLabelText('Email'),{target:{value:'host@example.test'}})
 fireEvent.change(screen.getByLabelText('Password'),{target:{value:'a long fixture password'}})
 fireEvent.click(screen.getByRole('button',{name:/Create account/}))
 await vi.waitFor(()=>expect(onLogin).toHaveBeenCalled())
 expect(api).toHaveBeenCalledWith('/auth/signup','POST',expect.objectContaining({setup_code:'river-stone-4821',email:'host@example.test'}))
 window.history.pushState({},'','/')
})
it('has no setup code field when the server does not ask for one',async()=>{
 vi.mocked(api).mockResolvedValue({setup:true,setup_code:false})
 render(<MemoryRouter><Welcome onLogin={vi.fn()}/></MemoryRouter>)
 fireEvent.click(await screen.findByRole('button',{name:/Create your Grove/}))
 expect(await screen.findByLabelText('Space name')).toBeInTheDocument()
 expect(screen.queryByLabelText('Setup code')).toBeNull()
})
it('a new Grove first asks whether to join one or create this one',async()=>{
 vi.mocked(api).mockResolvedValue({setup:true,setup_code:true})
 render(<MemoryRouter><Welcome onLogin={vi.fn()}/></MemoryRouter>)
 expect(await screen.findByRole('heading',{name:'Welcome to a new Grove'})).toBeInTheDocument()
 expect(screen.getByLabelText('Invitation link')).toBeInTheDocument()
 expect(screen.queryByLabelText('Your name')).toBeNull()
 fireEvent.click(screen.getByRole('button',{name:/Create your Grove/}))
 expect(screen.getByLabelText('Setup code')).toBeInTheDocument()
 fireEvent.click(screen.getByRole('button',{name:'Back'}))
 expect(screen.getByRole('heading',{name:'Welcome to a new Grove'})).toBeInTheDocument()
})
